[SERVICE]
    Flush 1
    Grace 1
    Log_Level info
    Parsers_File /fluent-bit/platform/parsers.conf
    storage.path /tmp/fluent-bit-test
    storage.max_chunks_up 2

[INPUT]
    Name stdin
    Tag ${TEST_PRODUCER}-firelens-test
    storage.type filesystem

@INCLUDE /fluent-bit/platform/routing.conf

[FILTER]
    Name modify
    Match audit
    Add test_destination archive

[FILTER]
    Name modify
    Match rejected
    Add test_destination rejected

[FILTER]
    Name modify
    Match *-firelens-*
    Add test_destination operational

[OUTPUT]
    Name stdout
    Match *
    Format json_lines
    json_date_key false
